name: mmpdemo

services:
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html

    environment:
      DB_HOST: db
      DB_PORT: 3306
      # TODO: Remove password fallbacks. INSECURE.
      DB_DATABASE: ${MYSQL_DATABASE:-mmpdemo}
      DB_USERNAME: ${MYSQL_USER:-mmpdemo}
      DB_PASSWORD: ${MYSQL_PASSWORD:-mmpdemo_dev}

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    
    # TODO: Remove DEVONLY port exposure here is unnecessary when all containers are running.
    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mmpdemo}
      MYSQL_USER: ${MYSQL_USER:-mmpdemo}
      # TODO: Remove password fallbacks. INSECURE.
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mmpdemo_dev}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mmpdemo_root}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: mysqladmin ping -h localhost -u root -p="$${MYSQL_ROOT_PASSWORD}"
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  mysql_data: {}
